<?php
/**
 * Admin - Image Management
 */
require_once 'includes/header.php';

$message = '';

// Handle delete
if (isset($_GET['delete'])) {
    $id = (int)$_GET['delete'];
    $img = $db->prepare("SELECT result_image FROM images WHERE id = ?");
    $img->execute([$id]);
    $image = $img->fetch();
    
    if ($image && file_exists('../../' . $image['result_image'])) {
        unlink('../../' . $image['result_image']);
    }
    $db->prepare("DELETE FROM images WHERE id = ?")->execute([$id]);
    $message = 'Image deleted successfully.';
}

// Filter by user
$userId = $_GET['user_id'] ?? null;
$query = "
    SELECT i.*, u.name as user_name, u.email as user_email
    FROM images i
    JOIN users u ON i.user_id = u.id
";
$params = [];

if ($userId) {
    $query .= " WHERE i.user_id = ?";
    $params = [$userId];
}

$query .= " ORDER BY i.created_at DESC";
$images = $db->prepare($query);
$images->execute($params);
$images = $images->fetchAll();
?>

<div class="main-content">
    <div class="page-header">
        <div>
            <h1>🖼️ Generated Images</h1>
            <p>View and manage user generated images</p>
        </div>
    </div>
    
    <?php if ($message): ?>
    <div class="alert alert-success"><?= htmlspecialchars($message) ?></div>
    <?php endif; ?>
    
    <div class="card">
        <div class="card-header">
            <h2>🖼️ All Images (<?= count($images) ?>)</h2>
        </div>
        <div class="card-body">
            <div class="gallery-grid">
                <?php foreach ($images as $image): ?>
                <div class="gallery-item">
                    <img src="../../<?= htmlspecialchars($image['result_image']) ?>" alt="Result" class="gallery-image">
                    <div class="gallery-info">
                        <h3><?= htmlspecialchars($image['user_name']) ?></h3>
                        <p><?= htmlspecialchars(substr($image['custom_text'] ?? 'No text', 0, 50)) ?>...</p>
                        <p style="font-size: 0.75em; color: #999; margin-bottom: 10px;"><?= date('M d, Y H:i', strtotime($image['created_at'])) ?></p>
                        <div class="gallery-actions">
                            <a href="../../<?= htmlspecialchars($image['result_image']) ?>" target="_blank" class="btn btn-small btn-info">View</a>
                            <a href="?delete=<?= $image['id'] ?>" class="btn btn-small btn-danger" onclick="return confirm('Delete this image?')">Delete</a>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            
            <?php if (empty($images)): ?>
            <div style="text-align: center; padding: 60px 20px;">
                <div style="font-size: 4em; margin-bottom: 20px;">🖼️</div>
                <h3 style="color: #1a1a2e; margin-bottom: 10px;">No Images Yet</h3>
                <p style="color: #666;">Images generated by users will appear here</p>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>

<?php require_once 'includes/footer.php'; ?>
